server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

live_store:
  max_trace_idle: 10s
  max_block_bytes: 1000000
  max_block_duration: 5m
  wal:
    path: /var/tempo/live-store/traces

backend_scheduler:
  provider:
    compaction:
      compaction:
        compaction_window: 1h
        max_block_bytes: 100000000
        block_retention: 1h
        compacted_block_retention: 10m

backend_worker:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100000000
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
